version: '3.8'

services:
  # Serviciul PostgreSQL
  postgres:
    image: postgres:15
    container_name: ama_postgres
    environment:
      POSTGRES_DB: ama_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Script de init a bazei de date
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ama_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ama_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviciul app web
  ama_app:
    build: .
    container_name: ama_webapp
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Variabile de mediu pentru conectarea la baza de date
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ama_db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_URL: jdbc:postgresql://postgres:5432/ama_db
    networks:
      - ama_network

volumes:
  postgres_data:

networks:
  ama_network:
    driver: bridge